# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "tkwk306"
description:        "tkwk306's blog"

# URL
url:                "http://yongjinshin306.github.io"
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:title.html

copyright:
  year:             2019
  name:             tkwk306

markdown: kramdown

kramdown:
  input: GFM
  parse_block_html: true


# Navigation
nav:
  - name:           "About"
    href:           "/about"
  - name:           "Tags"
    href:           "/tags"
  - name:           "Github"
    href:           "https://github.com/YongjinShin306"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# Timezone
timezone: "Asia/Seoul"

plugins:
  - jekyll-seo-tag
