# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "carpedm43"
description:        "carpedm43's blog"

# URL
url:                "http://carpedm43.github.io"
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:title.html

copyright:
  year:             2019
  name:             carpedm43

markdown: kramdown

kramdown:
  input: GFM
  parse_block_html: true


# Navigation
nav:
  - name:           "About"
    href:           "/about"
  - name:           "Tags"
    href:           "/tags"
  - name:           "Notion Blog"
    href:           "https://www.notion.so/hyeonbae/Notion-Blog-526372a9158943ce8cbb9bfe7957baed"
  - name:           "Github"
    href:           "https://github.com/carpedm43"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# Timezone
timezone: "Asia/Seoul"

plugins:
  - jekyll-seo-tag
